name: Keep Render Alive

on:
  schedule:
    - cron: "*/14 * * * *"   # every 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -s -o /dev/null -w "Status: %{http_code}\n" https://aurevox-lens.onrender.com
